version: 1.0.{build}

environment:
    matrix:
        - CMAKE_GENERATOR: MinGW Makefiles

install:
    - cinst mingw

before_build:
    - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
    - set PATH=C:\tools\mingw64\bin;%PATH%
    - mkdir build

build_script:
    - cmake -G "%CMAKE_GENERATOR%" -H. -Bbuild
    - cmake --build build
