version: 1.0.{build}

environment:
  matrix:
    - GENERATOR: MinGW Makefiles

install:
 - cinst mingw

build_script:
- ps: >-
    mkdir build
    cd build
    cmake -G "%GENERATOR%" ..
    cmake --build .
